Socket Class Reference
TCP/IP or UDP/Datagram IPv4 socket.
#include <ccsocket.h>
Public Types
enum Errors { Failed = -1
, InvalidSocket = -2
, UnknownHost = -3
 }
Socket errors.
Public Member Functions
Socket (int type=SOCK_STREAM)
Creates a new Socket. Creates a AF_INET socket using the IPv4 Internet protocol. Type can be:
Socket (int type, SOCKET sockfd)
Creates a Socket from an existing socket file descriptor.
~Socket ()
Destructor (closes the socket).
int connect (const std::string &host, int port)
Connects the socket to an address. Typically used for connecting TCP/IP clients to a ServerSocket. On Unix/Linux host can be a hostname, on Windows it can only be an IP address.
int bind (int port)
Assigns the socket to localhost.
int bind (const std::string &host, int port)
Assigns the socket to an IP address. On Unix/Linux host can be a hostname, on Windows it can only be an IP address.
int close ()
Closes the socket.
bool isClosed () const
Returns true if the socket has been closed.
SOCKET descriptor ()
Returns the descriptor of the socket.
void shutdownInput ()
Disables further receive operations.
void shutdownOutput ()
Disables further send operations.
SOCKSIZE send (const SOCKDATA *buf, size_t len, int flags=0)
Send sdata to a connected (TCP/IP) socket. Sends the first len bytes in buf.
SOCKSIZE receive (SOCKDATA *buf, size_t len, int flags=0)
Receives data from a connected (TCP/IP) socket. Reads at most len bytes fand stores them in buf. By default, this function blocks the caller until thre is availbale data.
SOCKSIZE sendTo (void const *buf, size_t len, int flags, SOCKADDR const *to, socklen_t addrlen)
Sends data to a datagram socket.
SOCKSIZE receiveFrom (void *buf, size_t len, int flags, SOCKADDR *from, socklen_t *addrlen)
Receives data from datagram socket.
int setReceiveBufferSize (int size)
Set the size of the TCP/IP input buffer.
int setReuseAddress (bool)
Enable/disable the SO_REUSEADDR socket option.
int setSendBufferSize (int size)
Set the size of the TCP/IP output buffer.
int setSoLinger (bool, int linger)
Enable/disable SO_LINGER with the specified linger time in seconds.
int setSoTimeout (int timeout)
Enable/disable SO_TIMEOUT with the specified timeout (in milliseconds).
int setTcpNoDelay (bool)
Enable/disable TCP_NODELAY (turns on/off TCP coalescence).
int getReceiveBufferSize () const
Return the size of the TCP/IP input buffer.
bool getReuseAddress () const
Return SO_REUSEADDR state.
int getSendBufferSize () const
Return the size of the TCP/IP output buffer.
bool getSoLinger (int &linger) const
Return SO_LINGER state and the specified linger time in seconds.
int getSoTimeout () const
Return SO_TIMEOUT value.
bool getTcpNoDelay () const
Return TCP_NODELAY state.
Static Public Member Functions
static void startup ()
initialisation and cleanup of sockets on Widows.
static void cleanup ()
Private Member Functions
int setLocalAddress (SOCKADDR_IN &addr, int port)
int setAddress (SOCKADDR_IN &addr, const std::string &host, int port)
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
Socket & operator= (Socket &&)=delete
Private Attributes
SOCKET sockfd_ {}
Friends
class ServerSocket
Detailed Description
TCP/IP or UDP/Datagram IPv4 socket.
AF_INET connections following the IPv4 Internet protocol are supported.
Note
ServerSocket should be used on the server side.
SIGPIPE signals are ignored when using Linux, BSD or MACOSX.
TCP/IP sockets do not preserve record boundaries but SocketBuffer solves this problem.
Definition at line 46 of file ccsocket.h.
Member Enumeration Documentation
Errors
enum Socket::Errors
Socket errors.
Socket::Failed (-1): could not connect, could not bind, etc.
Socket::InvalidSocket (-2): invalid socket or wrong socket type
Socket::UnknownHost (-3): could not reach host
Enumerator
Failed
InvalidSocket
UnknownHost
Definition at line 52 of file ccsocket.h.
Constructor & Destructor Documentation
Socket() [1/3]
Socket::Socket (int type = SOCK_STREAM)
Creates a new Socket. Creates a AF_INET socket using the IPv4 Internet protocol. Type can be:
SOCK_STREAM (the default) for TCP/IP connected stream sockets
SOCK_DGRAM for UDP/datagram sockets (available only or Unix/Linux)
Definition at line 48 of file ccsocket.cpp.
References sockfd_, and startup().
Socket() [2/3]
Socket::Socket (int type, SOCKET sockfd)
Creates a Socket from an existing socket file descriptor.
Definition at line 64 of file ccsocket.cpp.
References startup().
~Socket()
Socket::~Socket ()
Destructor (closes the socket).
Definition at line 68 of file ccsocket.cpp.
References close().
Socket() [3/3]
Socket::Socket (const Socket &) [private], [delete]
Member Function Documentation
bind() [1/2]
int Socket::bind (const std::string & host, int port)
Assigns the socket to an IP address. On Unix/Linux host can be a hostname, on Windows it can only be an IP address.
Returns
0 on success or a negative value on error, see Socket::Errors
bind() [2/2]
int Socket::bind (int port)
Assigns the socket to localhost.
Returns
0 on success or a negative value on error, see Socket::Errors
Definition at line 104 of file ccsocket.cpp.
References INVALID_SOCKET, InvalidSocket, setLocalAddress(), SOCKADDR, SOCKADDR_IN, and sockfd_.
cleanup()
void Socket::cleanup () [static]
Definition at line 37 of file ccsocket.cpp.
close()
int Socket::close ()
Closes the socket.
Definition at line 134 of file ccsocket.cpp.
References close(), INVALID_SOCKET, and sockfd_.
connect()
int Socket::connect (const std::string & host, int port)
Connects the socket to an address. Typically used for connecting TCP/IP clients to a ServerSocket. On Unix/Linux host can be a hostname, on Windows it can only be an IP address.
Returns
0 on success or a negative value on error which is one of Socket::Errors
Definition at line 124 of file ccsocket.cpp.
References INVALID_SOCKET, InvalidSocket, setAddress(), SOCKADDR, SOCKADDR_IN, sockfd_, and UnknownHost.
descriptor()
SOCKET Socket::descriptor () [inline]
Returns the descriptor of the socket.
Definition at line 95 of file ccsocket.h.
References sockfd_.
getReceiveBufferSize()
int Socket::getReceiveBufferSize () const
Return the size of the TCP/IP input buffer.
getReuseAddress()
bool Socket::getReuseAddress () const
Return SO_REUSEADDR state.
getSendBufferSize()
int Socket::getSendBufferSize () const
Return the size of the TCP/IP output buffer.
getSoLinger()
bool Socket::getSoLinger (int & linger) const
Return SO_LINGER state and the specified linger time in seconds.
getSoTimeout()
int Socket::getSoTimeout () const
Return SO_TIMEOUT value.
getTcpNoDelay()
bool Socket::getTcpNoDelay () const
Return TCP_NODELAY state.
isClosed()
bool Socket::isClosed () const [inline]
Returns true if the socket has been closed.
Definition at line 92 of file ccsocket.h.
References INVALID_SOCKET, and sockfd_.
operator=() [1/2]
Socket & Socket::operator= (const Socket &) [private], [delete]
operator=() [2/2]
Socket & Socket::operator= (Socket &&) [private], [delete]
receive()
SOCKSIZE Socket::receive (SOCKDATA * buf, size_t len, int flags = 0) [inline]
Receives data from a connected (TCP/IP) socket. Reads at most len bytes fand stores them in buf. By default, this function blocks the caller until thre is availbale data.
Returns
the number of bytes that were received, or 0 or shutdownOutput() was called on the other side, or Socket::Failed (-1) if an error occured.
Definition at line 117 of file ccsocket.h.
References sockfd_.
receiveFrom()
SOCKSIZE Socket::receiveFrom (void * buf, size_t len, int flags, SOCKADDR * from, socklen_t * addrlen) [inline]
Receives data from datagram socket.
Definition at line 130 of file ccsocket.h.
References sockfd_.
send()
SOCKSIZE Socket::send (const SOCKDATA * buf, size_t len, int flags = 0) [inline]
Send sdata to a connected (TCP/IP) socket. Sends the first len bytes in buf.
Returns
the number of bytes that were sent, or 0 or shutdownInput() was called on the other side, or Socket::Failed (-1) if an error occured.
Note
TCP/IP sockets do not preserve record boundaries, see SocketBuffer.
Definition at line 108 of file ccsocket.h.
References NO_SIGPIPE_, and sockfd_.
sendTo()
SOCKSIZE Socket::sendTo (void const * buf, size_t len, int flags, SOCKADDR const * to, socklen_t addrlen) [inline]
Sends data to a datagram socket.
Definition at line 124 of file ccsocket.h.
References NO_SIGPIPE_, and sockfd_.
setAddress()
int Socket::setAddress (SOCKADDR_IN & addr, const std::string & host, int port) [private]
Definition at line 84 of file ccsocket.cpp.
setLocalAddress()
int Socket::setLocalAddress (SOCKADDR_IN & addr, int port) [private]
Definition at line 74 of file ccsocket.cpp.
setReceiveBufferSize()
int Socket::setReceiveBufferSize (int size)
Set the size of the TCP/IP input buffer.
Definition at line 159 of file ccsocket.cpp.
References sockfd_.
setReuseAddress()
int Socket::setReuseAddress (bool state)
Enable/disable the SO_REUSEADDR socket option.
Definition at line 167 of file ccsocket.cpp.
References sockfd_.
setSendBufferSize()
int Socket::setSendBufferSize (int size)
Set the size of the TCP/IP output buffer.
Definition at line 163 of file ccsocket.cpp.
References sockfd_.
setSoLinger()
int Socket::setSoLinger (bool on, int linger)
Enable/disable SO_LINGER with the specified linger time in seconds.
Definition at line 172 of file ccsocket.cpp.
References sockfd_.
setSoTimeout()
int Socket::setSoTimeout (int timeout)
Enable/disable SO_TIMEOUT with the specified timeout (in milliseconds).
Definition at line 179 of file ccsocket.cpp.
References sockfd_.
setTcpNoDelay()
int Socket::setTcpNoDelay (bool state)
Enable/disable TCP_NODELAY (turns on/off TCP coalescence).
Definition at line 186 of file ccsocket.cpp.
References sockfd_.
shutdownInput()
void Socket::shutdownInput ()
Disables further receive operations.
Definition at line 149 of file ccsocket.cpp.
References sockfd_.
shutdownOutput()
void Socket::shutdownOutput ()
Disables further send operations.
Definition at line 153 of file ccsocket.cpp.
References sockfd_.
startup()
void Socket::startup () [static]
initialisation and cleanup of sockets on Widows.
Note
startup is automaticcaly called when a Socket or a ServerSocket is created
Definition at line 25 of file ccsocket.cpp.
Friends And Related Symbol Documentation
ServerSocket
friend class ServerSocket [friend]
Definition at line 174 of file ccsocket.h.
Member Data Documentation
sockfd_
SOCKET Socket::sockfd_ {} [private]
Definition at line 181 of file ccsocket.h.
The documentation for this class was generated from the following files:
ccsocket.h
ccsocket.cpp