SocketCnx Class Reference
Connection with a given client. Each SocketCnx uses a different thread.
Public Member Functions
SocketCnx (TCPServer &, Socket *)
~SocketCnx ()
void processRequests ()
Public Attributes
TCPServer & server_
Socket * sock_
SocketBuffer * sockbuf_
std::thread thread_
Detailed Description
Connection with a given client. Each SocketCnx uses a different thread.
Definition at line 14 of file tcpserver.cpp.
Constructor & Destructor Documentation
SocketCnx()
SocketCnx::SocketCnx (TCPServer & server, Socket * socket)
Definition at line 28 of file tcpserver.cpp.
References processRequests().
~SocketCnx()
SocketCnx::~SocketCnx ()
Definition at line 37 of file tcpserver.cpp.
References Socket::close(), sock_, and sockbuf_.
Member Function Documentation
processRequests()
void SocketCnx::processRequests ()
Definition at line 45 of file tcpserver.cpp.
References TCPServer::callback_, TCPServer::error(), SocketBuffer::readLine(), server_, sockbuf_, and SocketBuffer::writeLine().
Member Data Documentation
server_
TCPServer& SocketCnx::server_
Definition at line 21 of file tcpserver.cpp.
sock_
Socket* SocketCnx::sock_
Definition at line 22 of file tcpserver.cpp.
sockbuf_
SocketBuffer* SocketCnx::sockbuf_
Definition at line 23 of file tcpserver.cpp.
thread_
std::thread SocketCnx::thread_
Definition at line 24 of file tcpserver.cpp.
The documentation for this class was generated from the following file:
tcpserver.cpp