TCPServer Class Reference
TCP/IP IPv4 server. Supports TCP/IP AF_INET IPv4 connections with multiple clients. One thread is used per client.
#include <tcpserver.h>
Public Types
using Callback = std::function< bool(std::string const &request, std::string &response) >
Public Member Functions
TCPServer (Callback const &callback)
initializes the server. The callback function will be called each time the server receives a request from a client.
virtual ~TCPServer ()
virtual int run (int port)
Starts the server. Binds an internal ServerSocket to port then starts an infinite loop that processes connection requests from clients.
Private Member Functions
TCPServer (TCPServer const &)=delete
TCPServer & operator= (TCPServer const &)=delete
void error (std::string const &msg)
Private Attributes
ServerSocket servsock_
Callback callback_ {}
Friends
class TCPLock
class SocketCnx
Detailed Description
TCP/IP IPv4 server. Supports TCP/IP AF_INET IPv4 connections with multiple clients. One thread is used per client.
Definition at line 19 of file tcpserver.h.
Member Typedef Documentation
Callback
using TCPServer::Callback = std::function< bool(std::string const& request, std::string& response) >
Definition at line 22 of file tcpserver.h.
Constructor & Destructor Documentation
TCPServer() [1/2]
TCPServer::TCPServer (Callback const & callback)
initializes the server. The callback function will be called each time the server receives a request from a client.
request contains the data sent by the client
response will be sent to the client as a response The connection with the client is closed if the callback returns false.
Definition at line 94 of file tcpserver.cpp.
~TCPServer()
TCPServer::~TCPServer () [virtual]
Definition at line 99 of file tcpserver.cpp.
TCPServer() [2/2]
TCPServer::TCPServer (TCPServer const &) [private], [delete]
Member Function Documentation
error()
void TCPServer::error (std::string const & msg) [private]
Definition at line 120 of file tcpserver.cpp.
operator=()
TCPServer & TCPServer::operator= (TCPServer const &) [private], [delete]
run()
int TCPServer::run (int port) [virtual]
Starts the server. Binds an internal ServerSocket to port then starts an infinite loop that processes connection requests from clients.
Returns
0 on normal termination, or a negative value if the ServerSocket could not be bound (value is then one of Socket::Errors).
Definition at line 101 of file tcpserver.cpp.
References ServerSocket::accept(), ServerSocket::bind(), error(), servsock_, and SocketCnx.
Friends And Related Symbol Documentation
SocketCnx
friend class SocketCnx [friend]
Definition at line 43 of file tcpserver.h.
TCPLock
friend class TCPLock [friend]
Definition at line 42 of file tcpserver.h.
Member Data Documentation
callback_
Callback TCPServer::callback_ {} [private]
Definition at line 50 of file tcpserver.h.
servsock_
ServerSocket TCPServer::servsock_ [private]
Definition at line 49 of file tcpserver.h.
The documentation for this class was generated from the following files:
tcpserver.h
tcpserver.cpp