MainWindow Class Reference
Fenêtre principale du client multimédia avec interface Swing.
Public Member Functions
MainWindow ()
Constructeur - initialise et affiche la fenêtre principale.
Static Public Member Functions
static void main (String[] args)
Point d'entrée de l'application.
Private Member Functions
void initializeActions ()
Initialise toutes les actions de l'interface.
void envoyerCommande (String command)
Envoie une commande au serveur et affiche le résultat.
Private Attributes
JTextArea textArea
Zone de texte pour afficher les résultats et messages.
JTextField textField
Champ de texte pour entrer le nom d'un objet multimédia.
Client client
Cliente TCP connectée au serveur multimédia.
Action searchAction
Action pour rechercher un objet multimédia par nom.
Action playAction
Action pour lire/jouer un objet multimédia.
Action exitAction
Action pour quitter l'application.
Action addFileAction
Action pour ajouter un nouveau fichier multimédia.
Action quitAction
Action pour envoyer la commande QUIT au serveur.
Detailed Description
Fenêtre principale du client multimédia avec interface Swing.
   Crée une interface graphique complète incluant :
   - Menu fichier avec options de gestion
   - Barre d'outils avec boutons d'action
   - Zone de texte pour afficher les résultats et messages
   - Panneau de contrôle pour l'entrée utilisateur
   - Palette de sélection de fichiers pour ajouter des médias
Definition at line 30 of file MainWindow.java.
Constructor & Destructor Documentation
MainWindow()
MainWindow.MainWindow () [inline]
Constructeur - initialise et affiche la fenêtre principale.
   Configure :
   - L'apparence (L&F)
   - La connexion au serveur
   - Les actions et leurs raccourcis
   - L'interface utilisateur (menus, barre d'outils, panneaux)

   Affiche également un message d'erreur si le serveur est indisponible
Definition at line 82 of file MainWindow.java.
References addFileAction, client, exitAction, initializeActions(), playAction, quitAction, searchAction, textArea, and textField.
Member Function Documentation
envoyerCommande()
void MainWindow.envoyerCommande (String command) [inline], [private]
Envoie une commande au serveur et affiche le résultat.
   Envoie une commande texte au serveur via le client TCP,
   puis affiche la commande et la réponse dans la zone de texte.
Parameters
command La commande à envoyer au serveur
Note
Peut être utilisée pour toute commande reconnue par le serveur
Definition at line 238 of file MainWindow.java.
References client, Client.send(), and textArea.
initializeActions()
void MainWindow.initializeActions () [inline], [private]
Initialise toutes les actions de l'interface.
   Crée et configure les actions pour :
   - Ajouter un fichier multimédias avec sélecteur de fichiers
   - Rechercher un objet par son nom
   - Lire/jouer un objet multimédia
   - Quitter l'application
   - Arrêtrer le serveur
Note
Chaque action est liée à un bouton/menu et déclenche une logique spécifique
Definition at line 149 of file MainWindow.java.
References addFileAction, envoyerCommande(), exitAction, playAction, quitAction, searchAction, textArea, and textField.
main()
static void MainWindow.main (String[] args) [inline], [static]
Point d'entrée de l'application.
   Lance l'interface graphique sur le thread de distribution des
   événements Swing (EDT)
   pour assurer la sécurité des threads.
Parameters
args Argument non utilisé
Definition at line 255 of file MainWindow.java.
References MainWindow().
Member Data Documentation
addFileAction
Action MainWindow.addFileAction [private]
Action pour ajouter un nouveau fichier multimédia.
Definition at line 64 of file MainWindow.java.
client
Client MainWindow.client [private]
Cliente TCP connectée au serveur multimédia.
Definition at line 44 of file MainWindow.java.
exitAction
Action MainWindow.exitAction [private]
Action pour quitter l'application.
Definition at line 59 of file MainWindow.java.
playAction
Action MainWindow.playAction [private]
Action pour lire/jouer un objet multimédia.
Definition at line 54 of file MainWindow.java.
quitAction
Action MainWindow.quitAction [private]
Action pour envoyer la commande QUIT au serveur.
Definition at line 69 of file MainWindow.java.
searchAction
Action MainWindow.searchAction [private]
Action pour rechercher un objet multimédia par nom.
Definition at line 49 of file MainWindow.java.
textArea
JTextArea MainWindow.textArea [private]
Zone de texte pour afficher les résultats et messages.
Definition at line 34 of file MainWindow.java.
textField
JTextField MainWindow.textField [private]
Champ de texte pour entrer le nom d'un objet multimédia.
Definition at line 39 of file MainWindow.java.
The documentation for this class was generated from the following file:
MainWindow.java