client.cpp File Reference
#include <iostream>
#include <string>
#include <algorithm>
#include "ccsocket.h"
Functions
int main ()
Lit une requete depuis le Terminal, envoie cette requete au serveur, recupere sa reponse et l'affiche sur le Terminal. Noter que le programme bloque si le serveur ne repond pas.
Variables
static const std::string HOST = "127.0.0.1"
static const int PORT = 3331
Function Documentation
main()
int main ()
Lit une requete depuis le Terminal, envoie cette requete au serveur, recupere sa reponse et l'affiche sur le Terminal. Noter que le programme bloque si le serveur ne repond pas.
Definition at line 20 of file client.cpp.
References Socket::connect(), Socket::Failed, HOST, PORT, SocketBuffer::readLine(), Socket::UnknownHost, and SocketBuffer::writeLine().
Variable Documentation
HOST
const std::string HOST = "127.0.0.1" [static]
Definition at line 11 of file client.cpp.
PORT
const int PORT = 3331 [static]
Definition at line 12 of file client.cpp.